name: R-CMD-check

on:
  push:
  pull_request:

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libcurl4-gnutls-dev libxml2-dev libssl-dev
      - name: Install R dependencies
        run: |
          install.packages('remotes')
          remotes::install_deps(dependencies = TRUE)
          install.packages("rcmdcheck")
        shell: Rscript {0}
      - name: Check package
        run: |
          rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
